# Sudo required for doing docker build
sudo: required
services:
- docker

# Build the docker image
script:
- ./build/docker-build.sh

# If successful, see if we need to publish also
after_success:
- ./build/travis-publish.sh

# Environment variables needed when publishing
env:
  global:
  # DOCKER_USER
  - secure: wntkwkbo9FUaqtQ3Ee4SIJ6k4d40FJih3sO29srfjLRdPusYhFx2m12XprsveO7W37SrJE7m8YNAkW91qL6eIRVJ95attXM60YhULZpDIXrbA5y8r/jle/sv4S1gLunFH8ZMkJBDBQxlHr6Rr10tNtHovor8woMGdsnXC/RRIQqI4u4EJ/RUCIV4zeC0OELjWtQqICsgfGttkFJFm8EDsirux+aRg2y7TzHIOkh4IiW57QlVJmV5hHc0J5W51bkc1WQpyG0XYBfElAv5M6I2wVTfRiJT3ZLHHHN+Py7i3TLotCkOZ6ap9cuBTkuhbMBb2iD/zYZGvVymYY6eA2tgQGZSTeTyVMZQDtqhuYGfyMZ+uUqsZKL3b8/ZCJk4wyLO8B3TgN3S8krXqi88Z4jzpGqGN9B3sfoiZ3WNK++Ka805gf9VcJAUc2n6qs85qbQlbkhNveV3orLBR+LxLvGnPOl9QbAUayhXEk0WJoLzRIA99W92LgETuWn+6M9X1AujKc/zO7AQ6AnGL/FC+pbgvIn89+w3GzdO7k5/MENCL3jjl8U30djkqq3S3821h9ZXWHnQWYiR/wLdYZvw7n9HPLRVfkPTeJZJUjpXgA1J+MgTj/OQWbk6RlXilXf8QqMkmS6RVlmmIN/Jzx1CsPw5+ggLij/kNVdAntvhkZpwa24=
  # DOCKER_EMAIL
  - secure: YZHwD7eIvkbKGDiNK+KlA1m1f7mBf3C1De8wdbj36PG2/IZBMaqXYMjF6cKaV+2KIwHXMEJcoi21b1EGgAvGZGQrI86LKBAJKrXGxc4XPDOylK5u2348ZyBiduXp2qcy6QfIGjg0fBr5EGfzJYtb/09ZpWqpPxmMMgk1i9WlctbLRsRwEM9FW/NyDhFDor6CxCqi+Xx7sO9gUKbeS6f/4kZ+krv9a32G7e67mkV73+u8Zyg28oglyoEmyrVUKnCfGpFEZ8XuuiCmMFR8VP83YS6WzrY2iY851EpqM81aKAeraYOseh3s6x6EUKupg+Y+M+xVSPBnOOiScnvdQJKoI/CpJ+6XZbwisMFlAteq4FTqtcyPoe1Yd46lSpDmPCd419buNmVhkmu11dInwSpMq8MVfhK4RfFOcWxmLW5rqzvoHO5RJuu+qrUJto9/fY2PcVJyhOc57rp6zuKVYnaA+ImcUbBfqHx6v5MM/p43aUu4hz7aFeEvQ054BjtetmgzTQ1sCsm3jufjo8gd9oFfXnJ9VMW49N24nUmnknSImdZr7Fo5H0dNZa2QoDeLbbdHDpCWc1o9Gahpe55UGW10lrx/EEbTFcqGjM3PP0Nz0g6nbGHldojN8Oy9Cfztbm3d5xECbARBY4jul7JggUP3kTl5F84PTvOjyJxr4pTsa80=
  # DOCKER_PASS
  - secure: z5yn1eD5e2uA8IOHRrCoNQOCTJSJwCWaqG5AmTqvYjzT6fQBYhAJe7HpNmxTeNueFmEHFLuBUvBvBaAWumRdDNSsH0cgk7IXm8xJjQYXrT8nZXuTeUuYPMMHoGUCLuN0ZeCV11GLBAeUoKnGuv1msbfL8vjl29fy0YgIf6Vbx7h18jxNhUzJQvnJXfbSIJqs89br6TgOGV7E+F/TnYkDsPObQDcT7G5q6DrJ/X9jcXkNxGT16lkB/3Ep70DQiiQ9LMElhlQG2ZPMmUgyE284S9CYQpuD538ZFEjq3tKuVK3pSLPsBV+sgJvkFey/FJQDtifchkLe/zXnDxxuibzek4GxXyHYDSXRO18hQjgdpmuyivbdcTSkPLEj7djPR7gtPJRTbbc1lTI6nCrYkhDM5kxvw/PZExwz1gwPGQMfn8meokCITRhwTZkbvifjx4jSAXsIaCH/0dy1/3EnbqE9OVoca2x/IaE+H9P8zCKmFIfVxCiPhh7p1Ma4PA2dO30FgfeB6YlRly5fYtSUxMYyBLlbVvb1YAcApgOGLCN+Ywr3IYVOhq2nmehOH1LWWSWqvAW66QQX3AP+gKeQ58xo5GmqOYu6S6LtjCwhhVvtMDF15Hqu3Mbq0mmWE3fbuvpMyWtPVvmGvc0QaEZQrUcmZQmT6QyHYZMSd6odZTord2E=

